# Step 2: Set up the Flask backend
FROM python:3.9 AS backend

# Set the working directory for the backend
WORKDIR /app/backend

# Copy the backend requirements and install dependencies
COPY backend/restaurent_app/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire backend source code
COPY backend/restaurent_app/ ./

# Expose Flask port (8001)
EXPOSE 8001

# Command to run Flask
CMD ["python", "handler.py"]
